env:
  global:
    # browserstack username
    - secure: "NK8T/zqgBJ1anSB9X9sc3DpqXPYAdnhLpXrBd5zxEW3BLsg/bMdOtiVP6NPB5Nvk3osofXM6syrOSZnLzsC0Vx26f20HDb3xghuZHdTEMHZJC6AGxeHNAv8AAS5w3jVlbGP1PBEyu1buHn10nAvaRx27WspJtkRiozyJ/eriWHY="
    # browserstack API key
    - secure: "e9zX4nIbOsDOkQcg9kK9PF95+s/+1Nuf3vXFmTygZHkbK7tOpZHqHpKBfAbU2YjY7v85p3R/eKfx/bxRQgdjD3FH7kyH8+O9OxbIZjjXOPtmAQPtSX9tRzc9AnzPNN3NdpIiZjcvTmwtdWocxE6E2XlgVZMUti+U/xDsUP+/Lp4="
    # browserstack password
    - secure: "Ca/IpSeMiJorbKOR8bzuzSiK8Sge4hpNyiVi3x57ecc1YWSS8Pm6u3VYUzPSNxTXaZI9tdyAN1lqcC6Gws9+056qefFpcI/WweXCl6BXZT88V55MMn/UxFQcJ45L10RjSwQtHm+2kSVg23fqCCcfn4l2c1+y5zXgeZYKHOTOneQ="
language: node_js
node_js:
  - 0.10
install:
  - npm install --no-optional --loglevel warn
  - npm install -g bower grunt-cli --no-optional --loglevel warn
  - npm install -g browserstack-cli --no-optional --loglevel warn
  - bower install --quiet
before_script:
  - grunt build:test
  - mkdir ~/.browserstack
  - cp BrowserStackTunnel.jar ~/.browserstack/BrowserStackTunnel.jar
script:
  - grunt test --debug
